stages:
  - build-and-publish

variables:
  DOCKER_IMAGE: registry.gitflic.ru/project/ваш_ник/ваш_проект/garage-management
  DOCKERFILE_PATH: services/docker/backend.Dockerfile

build-and-publish:
  stage: build-and-publish
  script:
    # 1. Логинимся в реестр GitFlic
    - echo "$GITFLIC_TOKEN" | docker login registry.gitflic.ru -u "$GITFLIC_USER" --password-stdin

    # 2. Собираем образ
    - docker build -t $DOCKER_IMAGE -f $DOCKERFILE_PATH .

    # 3. Публикуем в реестр
    - docker push $DOCKER_IMAGE

  # Запускаем только при пуше в master
  only:
    - master

  # Очистка после выполнения
  after_script:
    - docker logout registry.gitflic.ru
