name: Build and Publish Docker Image
run-name: Build and Publish Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        env:
          DOCKER_PASSWORD: ${{ secrets.GITFLIC_TOKEN }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login registry.gitflic.ru \
            -u "${{ secrets.GITFLIC_USER }}" \
            --password-stdin

      - name: Build and Push Backend Image (multi-arch)
        if: contains(github.event.head_commit.modified, 'backend/') ||
          contains(github.event.head_commit.added, 'backend/') ||
          contains(github.event.head_commit.removed, 'backend/')
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64/v8 \
            -t ${{ secrets.DOCKER_IMAGE }} \
            -f services/docker/backend.Dockerfile \
            . \
            --push

      - name: Build and Push Frontend Image (multi-arch)
        if: contains(github.event.head_commit.modified, 'frontend/') ||
          contains(github.event.head_commit.added, 'frontend/') ||
          contains(github.event.head_commit.removed, 'frontend/')
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64/v8 \
            -t ${{ secrets.DOCKER_IMAGE_FRONTEND }} \
            -f services/docker/frontend.Dockerfile \
            . \
            --push

      - name: Docker Logout
        run: docker logout registry.gitflic.ru
