automation:
  id: complex_air_control
  name: "Комплексное управление воздухом"
  trigger:
    type: sensor_change
    sensor_id: DS18B20_ddd8f64d18e4
    operator: ">"
    value: 10
  action:
    type: turn_on
    device_id: test_actuator_0300589370e8
  enabled: true
