automation:
  id: complex_air_control
  name: "Комплексное управление воздухом"
  trigger:
    type: sensor_change
    sensor_id: CSS811_cc989158bdca
    operator: ">"
    value: 100
  action:
    type: turn_on
    device_id: test_actuator_4f545a198cb2
  enabled: true
