automation:
  id: complex_air_control
  name: "Комплексное управление воздухом"
  trigger:
    type: sensor_change
    sensor_id: CSS811_af48ed717589
    operator: ">"
    value: 100
  action:
    type: turn_off
    device_id: test_actuator_0300589370e8
  enabled: true
